---
abstract: 'A fast and easy way to integrate your apps with Facebook.'
author:
  - 'JT Smith <jt@plainblack.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Facebook-Graph
no_index:
  directory:
    - author.t
    - eg
requires:
  Any::Moose: 0.13
  AnyEvent::HTTP::LWP::UserAgent: 0.8
  DateTime: 0.61
  DateTime::Format::Strptime: 1.4000
  JSON: 2.16
  MIME::Base64::URLSafe: 0.01
  Ouch: 0.0400
  Test::More: 0
  URI: 1.54
resources:
  bugtracker: http://github.com/rizen/Facebook-Graph/issues
  repository: git://github.com/rizen/Facebook-Graph.git
version: 1.0500
